name: UiPath CI/CD

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      # UiPath pack
      # Run Tests
      # Deploy to both test and prod

      - name: Run a one-line script
        run: echo Hello from Octo Organization
