# Basic workflow for utilizing GitHub Actions for CI on UiPath projects

name: UiPath CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # UiPath account stored as a Secret in Github
  UIPATH_ACCOUNT: ${{ secrets.UIPATH_ACCOUNT }}
  # Password for the UiPath account stored as a Secret
  UIPATH_PASSWORD: ${{ secrets.UIPATH_PASSWORD }}
  # URL to the Orchestrator instance
  ORCHESTRATOR_URL: "https://cloud.uipath.com/"
  # Orchestrator tenant to deploy the project to
  ORCHESTRATOR_TENANT: "Shared"
  # Folder in UiPath Orchestrator, for Modern Folder use
  ORCHESTRATOR_FOLDER: "TestFolder"

jobs:
  # This workflow contains a single call to reusable workflow
  mikael-pipeline:
    uses: Mikael-RnD/ReusableWorkflows/.github/workflows/reusable1.yml@main
    with:
      orchestratorFolder: Shared
      orchestratorTenant: Default
    secrets:
      orchestratorUsername: ${{ secrets.UIPATH_ACCOUNT }}
      orchestratorPassword: ${{ secrets.UIPATH_PASSWORD }}
