name: 'Setup UiPath CLI'
description: 'Setup the UiPath CLI on the runner'

runs:
  using: "composite"
  steps:
    - run: |
             New-Item -Path "C:\\" -ItemType "directory" -Name "uipathcli";
             Invoke-WebRequest "https://www.myget.org/F/uipath-dev/api/v2/package/UiPath.CLI/1.0.7985.19721" -OutFile "${{ github.workspace }}\\cli.zip";
             Expand-Archive -LiteralPath "${{ github.workspace }}\\cli.Zip" -DestinationPath "${{ github.workspace }}\\uipathcli";
      shell: bash
