# This is a basic workflow to help you get started with Actions

name: UiPath Pull Request Validation

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      password:
        required: true

jobs:
  pr-validation:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/my-action@v1
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}
