# This is a basic workflow to help you get started with Actions

name: UiPath Pack And Analyze

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      tenant:
        required: false
        type: string
      orchestrator_url:
        required: false
        type: string
      username:
        required: false
        type: string
      project_path:
        required: true
        type: string
      output_type:
        required: true
        type: string
      output_path:
        required: true
        type: string
    secrets:
      password:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: PowerShell script
      # You may pin to the exact commit or the version.
      # uses: Amadevus/pwsh-script@1f1751bbf3d1a92127bfc6c32403283625880cbf
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        # PowerShell script to execute in Actions-hydrated context
        script: 'Import-Module PowerShellGet Register-PSRepository -Name "uipath-dev" -SourceLocation "https://www.myget.org/F/uipath-dev/api/v2" Install-Module -Name "UiPath.CLI" -RequiredVersion "1.0.7985.19721" -Repository "uipath-dev"' 
    
    - name: UiPath Pack
      run: uipcli.exe package pack "${{inputs.project_path}}" -o "${{github.workspace}}"  --autoVersion --outputType Process --notes "${{github.event.head_commit.message}}"

#      - name: UiPath Pack
#        run: uipcli.exe package pack "${{inputs.project_path}}" -o "${{github.workspace}}"   --libraryOrchestratorPassword ${{secrets.password}} --autoVersion --outputType Process --notes ${{github.}} 

