# Workflow for deploying UiPath project to Orchestrator

name: UiPath CI

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      password:
        required: true
        
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci-cd:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: UiPath Pack
        run: echo Packing!!!

      - name: UiPath Deploy
        run: echo Deploying!!!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
