# This is a basic workflow to help you get started with Actions

name: UiPath Pack And Analyze

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      tenant:
        required: false
        type: string
      orchestrator_url:
        required: false
        type: string
      username:
        required: false
        type: string
      project_path:
        required: true
        type: string
      output_type:
        required: true
        type: string
      output_path:
        required: true
        type: string
    secrets:
      password:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Get UiPath CLI
      run: |
             New-Item -Path "${{ github.workspace }}" -ItemType "directory" -Name "uipathcli";
             Invoke-WebRequest "https://www.myget.org/F/uipath-dev/api/v2/package/UiPath.CLI/1.0.7985.19721" -OutFile "${{ github.workspace }}\\cli.zip";
             Expand-Archive -LiteralPath "${{ github.workspace }}\\cli.Zip" -DestinationPath "${{ github.workspace }}\\uipathcli";
      
    - name: UiPath Pack
      run: uipcli.exe package pack "${{inputs.project_path}}" -o "${{github.workspace}}"  --autoVersion --outputType Process --notes "${{github.event.head_commit.message}}"

#      - name: UiPath Pack
#        run: uipcli.exe package pack "${{inputs.project_path}}" -o "${{github.workspace}}"   --libraryOrchestratorPassword ${{secrets.password}} --autoVersion --outputType Process --notes ${{github.}} 

