# This is a basic workflow to help you get started with Actions

name: UiPath Pack And Analyze

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      tenant:
        required: false
        type: string
      orchestrator_url:
        required: true
        type: string
      username:
        required: false
        type: string
      project_path:
        required: true
        type: string
      output_type:
        required: true
        type: string
      output_path:
        required: true
        type: string
    secrets:
      password:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Setup UiPath CLI
        run: nuget install UiPath.CLI -Version 1.0.7985.19721 -Source https://www.myget.org/F/uipath-dev/api/v3/index.json
      - name: Echo
        run: echo $GITHUB_WORKSPACE
      - name: UiPath Pack
        run: uipcli.exe package pack "${{inputs.project_path}}" -o "${{github.workspace}}" --libraryOrchestratorUrl ${{inputs.orchestrator_url}} --libraryOrchestratorTenant ${{inputs.tenant}} --libraryOrchestratorUsername ${{inputs.username}} --libraryOrchestratorPassword ${{secrets.password}} --autoVersion --outputType ${{inputs.output_type}} 
